
package payroll;

public class AddEmployeeDialog extends javax.swing.JDialog {

   
    public AddEmployeeDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
       initComponents();
    setLocationRelativeTo(null);
    
    CancelBtn.addActionListener(e -> dispose());
    
    SaveBtn.addActionListener(e -> {
        String id = EmpIDTxt.getText().trim();
        String name = FullNameTxt.getText().trim();
        String dept = DeptTxt.getText().trim();
        String pos = PosTxt.getText().trim();
        String type = (String) TypeCombo.getSelectedItem();
        String pay = PayTxt.getText().trim();
        String pass = new String(PassField.getPassword()).trim();
        
        if (id.isEmpty() || name.isEmpty() || dept.isEmpty() || 
            pos.isEmpty() || pay.isEmpty() || pass.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Please fill in all fields!", 
                "Missing Information", 
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        System.out.println("TODO-SQL: Save employee - ID: " + id + ", Name: " + name + ", Dept: " + dept + ", Pay: " + pay);

    javax.swing.JOptionPane.showMessageDialog(this, 
    "Employee saved! (SQL not yet connected)\n" + name, 
    "Success", 
    javax.swing.JOptionPane.INFORMATION_MESSAGE);
dispose();
    });
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        AddLbl = new javax.swing.JLabel();
        EmpIdLbl = new javax.swing.JLabel();
        EmpIDTxt = new javax.swing.JTextField();
        NameLbl = new javax.swing.JLabel();
        FullNameTxt = new javax.swing.JTextField();
        DeptLbl = new javax.swing.JLabel();
        DeptTxt = new javax.swing.JTextField();
        PosLbl = new javax.swing.JLabel();
        PosTxt = new javax.swing.JTextField();
        EmpTypeLbl = new javax.swing.JLabel();
        TypeCombo = new javax.swing.JComboBox<>();
        PayLbl = new javax.swing.JLabel();
        PayTxt = new javax.swing.JTextField();
        PassLBl = new javax.swing.JLabel();
        PassField = new javax.swing.JPasswordField();
        SaveBtn = new javax.swing.JButton();
        CancelBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(21, 24, 32));

        jPanel1.setBackground(new java.awt.Color(21, 24, 32));
        jPanel1.setForeground(new java.awt.Color(85, 93, 120));

        AddLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        AddLbl.setForeground(new java.awt.Color(255, 255, 255));
        AddLbl.setText("Add Employee");

        EmpIdLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        EmpIdLbl.setForeground(new java.awt.Color(85, 93, 120));
        EmpIdLbl.setText("Employee ID");

        EmpIDTxt.setBackground(new java.awt.Color(28, 32, 48));
        EmpIDTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpIDTxtActionPerformed(evt);
            }
        });

        NameLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NameLbl.setForeground(new java.awt.Color(85, 93, 120));
        NameLbl.setText("Full Name");

        FullNameTxt.setBackground(new java.awt.Color(28, 32, 48));

        DeptLbl.setForeground(new java.awt.Color(85, 93, 120));
        DeptLbl.setText("Department");

        DeptTxt.setBackground(new java.awt.Color(28, 32, 48));

        PosLbl.setForeground(new java.awt.Color(85, 93, 120));
        PosLbl.setText("Position");

        PosTxt.setBackground(new java.awt.Color(28, 32, 48));

        EmpTypeLbl.setForeground(new java.awt.Color(85, 93, 120));
        EmpTypeLbl.setText("Employment Type");

        TypeCombo.setBackground(new java.awt.Color(28, 32, 48));
        TypeCombo.setForeground(new java.awt.Color(85, 93, 120));
        TypeCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Full-Time", "Part-Time", "Intern" }));

        PayLbl.setForeground(new java.awt.Color(85, 93, 120));
        PayLbl.setText("Basic Pay");

        PayTxt.setBackground(new java.awt.Color(28, 32, 48));

        PassLBl.setForeground(new java.awt.Color(85, 93, 120));
        PassLBl.setText("Password");

        PassField.setBackground(new java.awt.Color(28, 32, 48));
        PassField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PassFieldActionPerformed(evt);
            }
        });

        SaveBtn.setBackground(new java.awt.Color(79, 142, 247));
        SaveBtn.setText("Save");

        CancelBtn.setBackground(new java.awt.Color(28, 32, 48));
        CancelBtn.setText("Cancel");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddLbl)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(EmpIdLbl)
                                .addGap(194, 194, 194))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PassField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PassLBl)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addComponent(SaveBtn))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(TypeCombo, javax.swing.GroupLayout.Alignment.LEADING, 0, 170, Short.MAX_VALUE)
                                        .addComponent(EmpTypeLbl, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(DeptLbl, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(EmpIDTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(DeptTxt, javax.swing.GroupLayout.Alignment.LEADING)))
                                .addGap(69, 69, 69)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NameLbl)
                            .addComponent(FullNameTxt)
                            .addComponent(PosLbl)
                            .addComponent(PosTxt)
                            .addComponent(PayLbl)
                            .addComponent(PayTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(CancelBtn))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(AddLbl)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmpIdLbl)
                    .addComponent(NameLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmpIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FullNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DeptLbl)
                    .addComponent(PosLbl))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PosTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DeptTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmpTypeLbl)
                    .addComponent(PayLbl))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PayTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(PassLBl)
                .addGap(18, 18, 18)
                .addComponent(PassField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaveBtn)
                    .addComponent(CancelBtn))
                .addContainerGap(98, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PassFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PassFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PassFieldActionPerformed

    private void EmpIDTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpIDTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmpIDTxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddEmployeeDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddEmployeeDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddEmployeeDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddEmployeeDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddEmployeeDialog dialog = new AddEmployeeDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddLbl;
    private javax.swing.JButton CancelBtn;
    private javax.swing.JLabel DeptLbl;
    private javax.swing.JTextField DeptTxt;
    private javax.swing.JTextField EmpIDTxt;
    private javax.swing.JLabel EmpIdLbl;
    private javax.swing.JLabel EmpTypeLbl;
    private javax.swing.JTextField FullNameTxt;
    private javax.swing.JLabel NameLbl;
    private javax.swing.JPasswordField PassField;
    private javax.swing.JLabel PassLBl;
    private javax.swing.JLabel PayLbl;
    private javax.swing.JTextField PayTxt;
    private javax.swing.JLabel PosLbl;
    private javax.swing.JTextField PosTxt;
    private javax.swing.JButton SaveBtn;
    private javax.swing.JComboBox<String> TypeCombo;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
