/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package payroll;

/**
 *
 * @author benzali
 */
public class PayslipDocPanel extends javax.swing.JPanel {

    /**
     * Creates new form PayslipDocPanel
     */
    public PayslipDocPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DocPanel = new javax.swing.JPanel();
        BackBtn = new javax.swing.JButton();
        DocCard = new javax.swing.JPanel();
        CorpLbl = new javax.swing.JLabel();
        PayslipMonthLbl = new javax.swing.JLabel();
        PaydateLbl = new javax.swing.JLabel();
        PayMethodLbl = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        EmpNameLbl = new javax.swing.JLabel();
        NameValueLbl = new javax.swing.JLabel();
        PosLbl = new javax.swing.JLabel();
        PosValueLbl = new javax.swing.JLabel();
        EmpTypeLbl = new javax.swing.JLabel();
        EmpTypeValueLbl = new javax.swing.JLabel();
        PayLbl = new javax.swing.JLabel();
        PayValueLbl = new javax.swing.JLabel();
        EmpIDLbl = new javax.swing.JLabel();
        EmpIDValueLbl = new javax.swing.JLabel();
        DeptLbl = new javax.swing.JLabel();
        DeptValueLbl = new javax.swing.JLabel();
        DaysLbl = new javax.swing.JLabel();
        DaysValueLbl = new javax.swing.JLabel();
        MethodLbl = new javax.swing.JLabel();
        MethodValueLbl = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        EarningsLbl = new javax.swing.JLabel();
        DeductionLbl = new javax.swing.JLabel();
        SalaryLbl = new javax.swing.JLabel();
        SalaryValueLbl = new javax.swing.JLabel();
        OvertimeLbl = new javax.swing.JLabel();
        OvertimeValueLbl = new javax.swing.JLabel();
        TranspoLbl = new javax.swing.JLabel();
        TranspoValueLbl = new javax.swing.JLabel();
        MealLbl = new javax.swing.JLabel();
        MealValueLbl = new javax.swing.JLabel();
        TaxLbl = new javax.swing.JLabel();
        TaxValueLbl = new javax.swing.JLabel();
        SSSLbl = new javax.swing.JLabel();
        SSSVAlueLbl = new javax.swing.JLabel();
        PhilLbl = new javax.swing.JLabel();
        PhilValueLbl = new javax.swing.JLabel();
        PagIbigLbl = new javax.swing.JLabel();
        PagIbigValueLbl = new javax.swing.JLabel();
        NetPayCard = new javax.swing.JPanel();
        TakeHomeLbl = new javax.swing.JLabel();
        PHPLbl = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1280, 800));

        DocPanel.setBackground(new java.awt.Color(13, 15, 20));
        DocPanel.setPreferredSize(new java.awt.Dimension(1280, 800));

        BackBtn.setBackground(new java.awt.Color(21, 24, 32));
        BackBtn.setForeground(new java.awt.Color(255, 255, 255));
        BackBtn.setText("<- Back");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });

        DocCard.setBackground(new java.awt.Color(21, 24, 32));
        DocCard.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        DocCard.setForeground(new java.awt.Color(37, 42, 56));

        CorpLbl.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        CorpLbl.setForeground(new java.awt.Color(255, 255, 255));
        CorpLbl.setText("CORP");

        PayslipMonthLbl.setForeground(new java.awt.Color(85, 93, 120));
        PayslipMonthLbl.setText("PaySlip · Month 2026");

        PaydateLbl.setForeground(new java.awt.Color(85, 93, 120));
        PaydateLbl.setText("PayDate:-");

        PayMethodLbl.setForeground(new java.awt.Color(85, 93, 120));
        PayMethodLbl.setText("Payment Method:Bank Transfer");

        EmpNameLbl.setForeground(new java.awt.Color(255, 255, 255));
        EmpNameLbl.setText("Employee Name");

        NameValueLbl.setText("-");

        PosLbl.setForeground(new java.awt.Color(255, 255, 255));
        PosLbl.setText("Position");

        PosValueLbl.setText("-");

        EmpTypeLbl.setForeground(new java.awt.Color(255, 255, 255));
        EmpTypeLbl.setText("Employment Type");

        EmpTypeValueLbl.setText("-");

        PayLbl.setForeground(new java.awt.Color(255, 255, 255));
        PayLbl.setText("Pay Date");

        PayValueLbl.setText("-");

        EmpIDLbl.setForeground(new java.awt.Color(255, 255, 255));
        EmpIDLbl.setText("Employee ID");

        EmpIDValueLbl.setText("-");

        DeptLbl.setForeground(new java.awt.Color(255, 255, 255));
        DeptLbl.setText("Department");

        DeptValueLbl.setText("-");

        DaysLbl.setForeground(new java.awt.Color(255, 255, 255));
        DaysLbl.setText("Working Days");

        DaysValueLbl.setText("-");

        MethodLbl.setForeground(new java.awt.Color(255, 255, 255));
        MethodLbl.setText("Payment Method");

        MethodValueLbl.setText("-");

        jSeparator2.setBackground(new java.awt.Color(21, 24, 32));
        jSeparator2.setForeground(new java.awt.Color(37, 42, 56));

        EarningsLbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        EarningsLbl.setForeground(new java.awt.Color(85, 93, 120));
        EarningsLbl.setText("EARNINGS");

        DeductionLbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        DeductionLbl.setForeground(new java.awt.Color(85, 93, 120));
        DeductionLbl.setText("DEDUCTION");

        SalaryLbl.setForeground(new java.awt.Color(255, 255, 255));
        SalaryLbl.setText("Basic Salary");

        SalaryValueLbl.setText("-");

        OvertimeLbl.setForeground(new java.awt.Color(255, 255, 255));
        OvertimeLbl.setText("Overtime Pay");

        OvertimeValueLbl.setText("-");

        TranspoLbl.setForeground(new java.awt.Color(255, 255, 255));
        TranspoLbl.setText("Transport Allowance");

        TranspoValueLbl.setText("-");

        MealLbl.setForeground(new java.awt.Color(255, 255, 255));
        MealLbl.setText("Meal Allowance");

        MealValueLbl.setText("-");

        TaxLbl.setForeground(new java.awt.Color(255, 255, 255));
        TaxLbl.setText("Tax");

        TaxValueLbl.setForeground(new java.awt.Color(232, 234, 240));
        TaxValueLbl.setText("-");

        SSSLbl.setForeground(new java.awt.Color(255, 255, 255));
        SSSLbl.setText("SSS");

        SSSVAlueLbl.setText("-");

        PhilLbl.setForeground(new java.awt.Color(255, 255, 255));
        PhilLbl.setText("PhilHealth ");

        PhilValueLbl.setText("-");

        PagIbigLbl.setForeground(new java.awt.Color(255, 255, 255));
        PagIbigLbl.setText("Pag-IBIG");

        PagIbigValueLbl.setText("-");

        NetPayCard.setBackground(new java.awt.Color(28, 32, 48));
        NetPayCard.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        TakeHomeLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TakeHomeLbl.setForeground(new java.awt.Color(51, 153, 255));
        TakeHomeLbl.setText("NET TAKE HOME PAY");

        PHPLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        PHPLbl.setForeground(new java.awt.Color(51, 153, 255));
        PHPLbl.setText("PHP");

        javax.swing.GroupLayout NetPayCardLayout = new javax.swing.GroupLayout(NetPayCard);
        NetPayCard.setLayout(NetPayCardLayout);
        NetPayCardLayout.setHorizontalGroup(
            NetPayCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NetPayCardLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(TakeHomeLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 668, Short.MAX_VALUE)
                .addComponent(PHPLbl)
                .addGap(70, 70, 70))
        );
        NetPayCardLayout.setVerticalGroup(
            NetPayCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NetPayCardLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(NetPayCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TakeHomeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PHPLbl))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout DocCardLayout = new javax.swing.GroupLayout(DocCard);
        DocCard.setLayout(DocCardLayout);
        DocCardLayout.setHorizontalGroup(
            DocCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DocCardLayout.createSequentialGroup()
                .addGroup(DocCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DocCardLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(DocCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EmpNameLbl)
                            .addComponent(PosLbl)
                            .addComponent(EmpTypeLbl)
                            .addComponent(PayLbl))
                        .addGap(214, 214, 214)
                        .addGroup(DocCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NameValueLbl)
                            .addComponent(PosValueLbl)
                            .addComponent(EmpTypeValueLbl)
                            .addComponent(PayValueLbl))
                        .addGap(251, 251, 251)
                        .addGroup(DocCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EmpIDLbl)
                            .addComponent(DeptLbl)
                            .addComponent(DaysLbl)
                            .addComponent(MethodLbl))
                        .addGap(216, 216, 216)
                        .addGroup(DocCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MethodValueLbl)
                            .addComponent(DaysValueLbl)
                            .addComponent(DeptValueLbl)
                            .addComponent(EmpIDValueLbl)))
                    .addGroup(DocCardLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(DocCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EarningsLbl)
                            .addGroup(DocCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, DocCardLayout.createSequentialGroup()
                                    .addComponent(MealLbl)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(MealValueLbl))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, DocCardLayout.createSequentialGroup()
                                    .addGroup(DocCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(SalaryLbl)
                                        .addComponent(OvertimeLbl)
                                        .addComponent(TranspoLbl))
                                    .addGap(107, 107, 107)
                                    .addGroup(DocCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(TranspoValueLbl)
                                        .addComponent(OvertimeValueLbl)
                                        .addComponent(SalaryValueLbl)))))
                        .addGap(344, 344, 344)
                        .addGroup(DocCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SSSLbl)
                            .addComponent(DeductionLbl)
                            .addComponent(PhilLbl)
                            .addComponent(PagIbigLbl)
                            .addComponent(TaxLbl))
                        .addGap(249, 249, 249)
                        .addGroup(DocCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TaxValueLbl)
                            .addComponent(SSSVAlueLbl)
                            .addComponent(PhilValueLbl)
                            .addComponent(PagIbigValueLbl)))
                    .addGroup(DocCardLayout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(NetPayCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(149, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DocCardLayout.createSequentialGroup()
                .addGroup(DocCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, DocCardLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator2))
                    .addGroup(DocCardLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, DocCardLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(DocCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CorpLbl)
                            .addComponent(PayslipMonthLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(DocCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PaydateLbl)
                            .addComponent(PayMethodLbl))))
                .addGap(139, 139, 139))
        );
        DocCardLayout.setVerticalGroup(
            DocCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DocCardLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(DocCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CorpLbl)
                    .addComponent(PaydateLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DocCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PayslipMonthLbl)
                    .addComponent(PayMethodLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(DocCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmpNameLbl)
                    .addComponent(NameValueLbl)
                    .addComponent(EmpIDLbl)
                    .addComponent(EmpIDValueLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DocCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PosLbl)
                    .addComponent(PosValueLbl)
                    .addComponent(DeptLbl)
                    .addComponent(DeptValueLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DocCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmpTypeLbl)
                    .addComponent(EmpTypeValueLbl)
                    .addComponent(DaysLbl)
                    .addComponent(DaysValueLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DocCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PayLbl)
                    .addComponent(PayValueLbl)
                    .addComponent(MethodLbl)
                    .addComponent(MethodValueLbl))
                .addGap(42, 42, 42)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(DocCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EarningsLbl)
                    .addComponent(DeductionLbl))
                .addGap(18, 18, 18)
                .addGroup(DocCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SalaryLbl)
                    .addComponent(SalaryValueLbl)
                    .addComponent(TaxLbl)
                    .addComponent(TaxValueLbl))
                .addGap(18, 18, 18)
                .addGroup(DocCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OvertimeLbl)
                    .addComponent(OvertimeValueLbl)
                    .addComponent(SSSLbl)
                    .addComponent(SSSVAlueLbl))
                .addGap(18, 18, 18)
                .addGroup(DocCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TranspoLbl)
                    .addComponent(TranspoValueLbl)
                    .addComponent(PhilLbl)
                    .addComponent(PhilValueLbl))
                .addGap(18, 18, 18)
                .addGroup(DocCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MealLbl)
                    .addComponent(MealValueLbl)
                    .addComponent(PagIbigLbl)
                    .addComponent(PagIbigValueLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(NetPayCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout DocPanelLayout = new javax.swing.GroupLayout(DocPanel);
        DocPanel.setLayout(DocPanelLayout);
        DocPanelLayout.setHorizontalGroup(
            DocPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DocPanelLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(DocPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DocCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DocPanelLayout.setVerticalGroup(
            DocPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DocPanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(BackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(DocCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DocPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1279, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(DocPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BackBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BackBtn;
    private javax.swing.JLabel CorpLbl;
    private javax.swing.JLabel DaysLbl;
    private javax.swing.JLabel DaysValueLbl;
    private javax.swing.JLabel DeductionLbl;
    private javax.swing.JLabel DeptLbl;
    private javax.swing.JLabel DeptValueLbl;
    private javax.swing.JPanel DocCard;
    private javax.swing.JPanel DocPanel;
    private javax.swing.JLabel EarningsLbl;
    private javax.swing.JLabel EmpIDLbl;
    private javax.swing.JLabel EmpIDValueLbl;
    private javax.swing.JLabel EmpNameLbl;
    private javax.swing.JLabel EmpTypeLbl;
    private javax.swing.JLabel EmpTypeValueLbl;
    private javax.swing.JLabel MealLbl;
    private javax.swing.JLabel MealValueLbl;
    private javax.swing.JLabel MethodLbl;
    private javax.swing.JLabel MethodValueLbl;
    private javax.swing.JLabel NameValueLbl;
    private javax.swing.JPanel NetPayCard;
    private javax.swing.JLabel OvertimeLbl;
    private javax.swing.JLabel OvertimeValueLbl;
    private javax.swing.JLabel PHPLbl;
    private javax.swing.JLabel PagIbigLbl;
    private javax.swing.JLabel PagIbigValueLbl;
    private javax.swing.JLabel PayLbl;
    private javax.swing.JLabel PayMethodLbl;
    private javax.swing.JLabel PayValueLbl;
    private javax.swing.JLabel PaydateLbl;
    private javax.swing.JLabel PayslipMonthLbl;
    private javax.swing.JLabel PhilLbl;
    private javax.swing.JLabel PhilValueLbl;
    private javax.swing.JLabel PosLbl;
    private javax.swing.JLabel PosValueLbl;
    private javax.swing.JLabel SSSLbl;
    private javax.swing.JLabel SSSVAlueLbl;
    private javax.swing.JLabel SalaryLbl;
    private javax.swing.JLabel SalaryValueLbl;
    private javax.swing.JLabel TakeHomeLbl;
    private javax.swing.JLabel TaxLbl;
    private javax.swing.JLabel TaxValueLbl;
    private javax.swing.JLabel TranspoLbl;
    private javax.swing.JLabel TranspoValueLbl;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
